---
# Tasks for docker installation in remotes hosts from Jinja2 scrit
- name : "Install Docker from Jinja2 script"
  template:
    src: "docker_install.sh.j2"
    dest: "/home/{{ ansible_user }}/docker_install.sh"

- name: "Execute Install Script"
  command: "sh /home/{{ ansible_user }}/docker_install.sh"

<<<<<<< HEAD
- name: "Install EPEL repo"
  package: 
    name: "{{ item }}"
    state: "present"
  when: 'ansible_distribution == "CentOS"'
  loop:
    - "epel-release"

=======
# Adding EPL repository for CentOs distribution
- name: "Install EPEL repository"
  package: 
    name: "{{ item }}"
    state: "present"
  when: ansible_distribution == "CentOS"
  loop:
    - "epel-release"
 
 # Installation prerequietes before installing docker-py
>>>>>>> 47e99835c658f9b1bbba9f296c73a2905614c416
- name: "Download pip script"
  get_url:
    url: "https://bootstrap.pypa.io/pip/2.7/get-pip.py"
    dest: "/tmp/get-pip.py"
<<<<<<< HEAD
  when: 'ansible_distribution == "CentOS"'

- name: "Install python-pip"
  command: "'python2.7' '/tmp/get-pip.py'"
  when: 'ansible_distribution == "CentOS"'

# Docker-py Installation

- name : "Install python pip3 for Ubuntu"
  package:
    name: "python3-pip"
    state: "present"
  when: 'ansible_distribution == "Ubuntu"'
=======
  when: ansible_distribution == "CentOS"

- name: "Install python-pip for CentOS"
  command: "python2.7" "/tmp/get-pip.py"
  when: ansible_distribution == "CentOS"

- name : "Install python pip3 for Ubuntu"
  package:
    name: "python3-pip"
    state: present
  when: ansible_distribution == "Ubuntu"
>>>>>>> 47e99835c658f9b1bbba9f296c73a2905614c416

# Installation docker-py using pip package modules
- name: "Install docker-py via pip"
  pip:
    name: "docker-py"
    state: "present"

<<<<<<< HEAD
- name: "Enable and start Docker"
=======
# Start Docker service
- name: Enable and start Docker
>>>>>>> 47e99835c658f9b1bbba9f296c73a2905614c416
  service:
    name: "docker"
    enabled: "yes"
    state: "started"
  tags:
    - "docker"
