---
# Tasks for docker installation in remotes hosts from Jinja2 scrit
- name : "Install Docker from Jinja2 script"
  template:
    src: "docker_install.sh.j2"
    dest: "/home/{{ ansible_user }}/docker_install.sh"

- name: "Execute Install Script"
  command: "sh /home/{{ ansible_user }}/docker_install.sh"

# Installation docker-py using ansible pip modules
- name: "Install docker-py via pip"
  pip:
    name: "docker-py"
    state: "present"

# Start Docker service
- name: "Enable and start Docker"
  service:
    name: "docker"
    enabled: "yes"
    state: "started"
  tags:
    - "docker"
